# frozen_string_literal: true

require "fileutils"
require "open3"

module Aias
  class CrontabManager
    IDENTIFIER = "aias"
    LOG_BASE   = File.expand_path("~/.aia/schedule/logs")

    # Whenever marker comment pattern (without timestamp)
    BLOCK_OPEN_RE  = /^# Begin Whenever generated tasks for: #{IDENTIFIER}/
    BLOCK_CLOSE_RE = /^# End Whenever generated tasks for: #{IDENTIFIER}/

    # Parses cron lines generated by JobBuilder:
    #   <cron_expr>  <shell> -l -c "aia <prompt_id> >> <log_path> 2>&1"
    # [^\/\n]+ greedily captures all cron fields (they contain no '/') up to
    # the shell binary path which starts with '/'.
    ENTRY_RE = /^(?<cron>[^\/\n]+)\s+\/\S+\s+-l\s+-c\s+"aia\s+(?<prompt_id>\S+)\s+>>\s+(?<log>\S+)\s+2>&1/

    # Installs the combined whenever DSL into the user's crontab.
    # Creates the log base directory first if it does not exist.
    # Raises Aias::Error if whenever fails to write the crontab.
    def install(dsl_string)
      FileUtils.mkdir_p(LOG_BASE)
      result = Whenever::CommandLine.execute(
        string:     dsl_string,
        file:       File::NULL,
        update:     true,
        identifier: IDENTIFIER,
        console:    false
      )
      raise Aias::Error, "whenever failed to update crontab" unless result.zero?
    end

    # Removes all aias-managed entries from the crontab.
    # Non-aias entries are not touched.
    def clear
      Whenever::CommandLine.execute(
        clear:      true,
        identifier: IDENTIFIER,
        console:    false
      )
    end

    # Returns the whenever DSL converted to cron syntax without touching the
    # crontab. Useful for `aias dry-run`.
    def dry_run(dsl_string)
      Whenever.cron(string: dsl_string)
    end

    # Returns the raw text of the aias-managed block currently in the crontab.
    # Returns an empty string when no block exists.
    def current_block
      crontab = read_crontab
      in_block = false
      lines = []

      crontab.each_line do |line|
        if line.match?(BLOCK_OPEN_RE)
          in_block = true
          next
        end
        if line.match?(BLOCK_CLOSE_RE)
          in_block = false
          next
        end
        lines << line if in_block
      end

      lines.join
    end

    # Returns an Array of Hashes describing each installed aias cron job.
    # Each hash has :prompt_id, :cron_expr, and :log_path keys.
    def installed_jobs
      current_block.each_line.filter_map do |line|
        line = line.strip
        next if line.empty? || line.start_with?("#")
        match = ENTRY_RE.match(line)
        next unless match

        {
          prompt_id: match[:prompt_id],
          cron_expr: match[:cron].strip,
          log_path:  match[:log]
        }
      end
    end

    # Creates subdirectory structure under LOG_BASE for each prompt_id.
    # Called by CLI before install to ensure log dirs exist.
    def ensure_log_directories(prompt_ids)
      prompt_ids.each do |id|
        FileUtils.mkdir_p(File.dirname(File.join(LOG_BASE, "#{id}.log")))
      end
    end

    private

    # Reads the current crontab. Returns '' when no crontab exists.
    def read_crontab
      out, _err, status = Open3.capture3("crontab", "-l")
      status.success? ? out : ""
    end
  end
end
