# frozen_string_literal: true

require "fileutils"
require "open3"

module Aias
  class CrontabManager
    IDENTIFIER = "aias"
    LOG_BASE   = File.expand_path("~/.aia/schedule/logs")

    BLOCK_OPEN  = "# BEGIN aias"
    BLOCK_CLOSE = "# END aias"

    # Parses cron lines generated by JobBuilder:
    #   <cron_expr>  <shell> -l -c 'aia [--prompts-dir DIR] <prompt_id> >> <log> 2>&1'
    # [^\/\n]+ greedily captures all cron fields (they contain no '/') up to
    # the shell binary path which starts with '/'.
    # The optional --prompts-dir flag is skipped so prompt_id is always captured.
    ENTRY_RE = /^(?<cron>[^\/\n]+)\s+\/\S+\s+-l\s+-c\s+['"]aia\s+(?:--prompts-dir\s+\S+\s+)?(?<prompt_id>\S+)\s+>>\s+(?<log>\S+)\s+2>&1/

    def initialize(crontab_command: "crontab", log_base: LOG_BASE)
      @crontab_command = crontab_command
      @log_base        = log_base
    end

    # Installs the given cron lines into the user's crontab, replacing any
    # previously installed aias block. Creates the log base directory first.
    # Raises Aias::Error if the crontab write fails.
    def install(cron_lines)
      FileUtils.mkdir_p(@log_base)
      updated = replace_block(read_crontab, Array(cron_lines))
      write_crontab(updated)
    end

    # Removes the aias-managed block from the crontab.
    # Non-aias entries are not touched.
    def clear
      write_crontab(remove_block(read_crontab))
    end

    # Returns the cron lines as they would be written, without touching the
    # crontab. Useful for `aias dry-run`.
    def dry_run(cron_lines)
      Array(cron_lines).join("\n")
    end

    # Returns the raw text of the aias-managed block currently in the crontab
    # (markers excluded). Returns an empty string when no block exists.
    def current_block
      in_block = false
      lines    = []

      read_crontab.each_line do |line|
        if line.chomp == BLOCK_OPEN
          in_block = true
        elsif line.chomp == BLOCK_CLOSE
          in_block = false
        elsif in_block
          lines << line
        end
      end

      lines.join
    end

    # Returns an Array of Hashes describing each installed aias cron job.
    # Each hash has :prompt_id, :cron_expr, and :log_path keys.
    def installed_jobs
      current_block.each_line.filter_map do |line|
        line = line.strip
        next if line.empty? || line.start_with?("#")

        match = ENTRY_RE.match(line)
        next unless match

        {
          prompt_id: match[:prompt_id],
          cron_expr: match[:cron].strip,
          log_path:  match[:log]
        }
      end
    end

    # Inserts or replaces a single cron job in the aias block (upsert).
    # Any existing entry whose prompt_id matches is removed first, then the
    # new line is appended. All other managed entries are left untouched.
    # Raises Aias::Error if the crontab write fails.
    def add_job(cron_line, prompt_id)
      FileUtils.mkdir_p(@log_base)
      current  = read_crontab
      existing = current_block.each_line.map(&:chomp).reject(&:empty?)
      updated  = existing.reject { |l| ENTRY_RE.match(l)&.[](:prompt_id) == prompt_id }
      updated << cron_line
      write_crontab(replace_block(current, updated))
    end

    # Creates subdirectory structure under @log_base for each prompt_id.
    # Called by CLI before install to ensure log dirs exist.
    def ensure_log_directories(prompt_ids)
      prompt_ids.each do |id|
        FileUtils.mkdir_p(File.dirname(File.join(@log_base, "#{id}.log")))
      end
    end

    private

    # Reads the current crontab. Returns '' when no crontab exists.
    def read_crontab
      out, _err, status = Open3.capture3(@crontab_command, "-l")
      status.success? ? out : ""
    end

    # Writes content to the crontab via stdin.
    # Raises Aias::Error if the crontab command exits non-zero.
    def write_crontab(content)
      Open3.popen2(@crontab_command, "-") do |stdin, _stdout, thr|
        stdin.write(content)
        stdin.close
        raise Aias::Error, "failed to write crontab" unless thr.value.success?
      end
    end

    # Removes the aias block from content, leaving other lines intact.
    def remove_block(content)
      in_block = false
      lines    = content.each_line.reject do |line|
        if line.chomp == BLOCK_OPEN
          in_block = true
        elsif line.chomp == BLOCK_CLOSE
          in_block = false
        else
          next in_block
        end
        true
      end
      lines.join
    end

    # Removes any existing aias block then appends a fresh one.
    def replace_block(content, cron_lines)
      cleaned   = remove_block(content)
      new_block = ([BLOCK_OPEN] + cron_lines + [BLOCK_CLOSE]).join("\n") + "\n"
      cleaned.empty? ? new_block : cleaned.rstrip + "\n\n" + new_block
    end
  end
end
